#!/bin/bash

# StreakPair Authentication Secrets Setup Script
# This script will display the exact values you need to add to Replit Secrets

echo ""
echo "🔐 StreakPair Authentication Setup"
echo "=================================="
echo ""
echo "Please add these 3 secrets to your Replit Secrets panel:"
echo "(Click the lock 🔒 icon in the left sidebar)"
echo ""
echo "----------------------------------------"
echo "Secret 1:"
echo "Key: BETTER_AUTH_SECRET"
echo "Value: R8H8h+MfNG3Bzr3UK8NbDjgkVwMcXKLj21yNCHVlTf4="
echo ""
echo "----------------------------------------"
echo "Secret 2:"
echo "Key: BETTER_AUTH_URL"
echo "Value: https://488ec54f-a100-42c3-aa09-4cfb0c461cef-00-2t4wavj8fxqy0.riker.replit.dev"
echo ""
echo "----------------------------------------"
echo "Secret 3:"
echo "Key: NEXT_PUBLIC_BETTER_AUTH_URL"
echo "Value: https://488ec54f-a100-42c3-aa09-4cfb0c461cef-00-2t4wavj8fxqy0.riker.replit.dev"
echo ""
echo "=========================================="
echo ""
echo "Instructions:"
echo "1. Click the lock 🔒 icon in Replit's left sidebar"
echo "2. Click 'Add new secret'"
echo "3. Copy and paste each Key and Value exactly as shown"
echo "4. After adding all 3, restart your app (Stop → Run)"
echo ""
echo "✨ Once done, you'll be able to create accounts and use StreakPair!"
echo ""